### PR TITLE
Landing page juice box

### PR DESCRIPTION
**Pull request by Mati0x**
#317

### CODE REVIEW

**Comment by Corantin** [comment]
I tried with the svg version pulled from figma and it looks better resolution:
image
image

**Comment by Corantin** [comment]
But I very like 👍

**Comment by Mati0x** [comment]
> But I very like 👍

It was a placeholder image, i created a new cool one hehe. Thanks for feedback goss!

**Comment by Corantin** [comment]
> I tried with the svg version pulled from figma and it looks better resolution: image image

just saw the new image

**Comment by Corantin** [comment]
App button

**Review by Corantin — APPROVED** [review]

**Pull request merged**
