### PR TITLE
Fix new created entity outlined 

### PR DESCRIPTION
**Pull request by Corantin**
This pull request includes several changes to the `apps/web` directory, focusing on refactoring, bug fixes, and improving data fetching and handling. Key changes include removing unused imports, refactoring hooks, and updating components to handle metadata more efficiently.

### Refactoring and Code Cleanup:

* Removed unused imports and refactored the `getProposals` function in `apps/web/actions/getProposals.ts` to streamline the codebase.
* Updated imports to use the new context path for `useCollectQueryParams` in multiple files. ([apps/web/app/(app)/gardens/[chain]/[garden]/[community]/[poolId]/page.tsxL15-R15](diffhunk://#diff-61362aff1ab8473768382f4bd8c056d2855f68902284980e5d4532a7d62f6273L15-R15), [apps/web/app/(app)/gardens/[chain]/[garden]/[community]/page.tsxL37-R37](diffhunk://#diff-49d5384f5def8ff80efb455d684c80f0dcdab8bf772fc0bf2263438883ad9301L37-R37), [apps/web/app/(app)/gardens/[chain]/[garden]/page.tsxL29-R29](diffhunk://#diff-dc27544e161ab8a5b910e0e97e0db6bd0106657fc82c2f9cff2f575e3e57c11eL29-R29), [[1]](diffhunk://#diff-d48a7949ce0cb05061b61ee75776e65d5ff866460cacc7dab23c25e54ed1acc3L11-R11) [[2]](diffhunk://#diff-a20088c6c867d02437c772b5ce806d976d8dedeec1649e30faf56b405cf8db3cL20-R20)
* Removed the `tokenAddress` prop from `ProposalForm` component and updated related code to use `poolTokenAddr` instead. [[1]](diffhunk://#diff-9f2974bf619e035b43f2ad6d4c3ae53c0943d8e2d516380051a4fdcb38314d0bL45) [[2]](diffhunk://#diff-9f2974bf619e035b43f2ad6d4c3ae53c0943d8e2d516380051a4fdcb38314d0bL119) [[3]](diffhunk://#diff-9f2974bf619e035b43f2ad6d4c3ae53c0943d8e2d516380051a4fdcb38314d0bL268-R265) [[4]](diffhunk://#diff-9f2974bf619e035b43f2ad6d4c3ae53c0943d8e2d516380051a4fdcb38314d0bL278-L290)

### Bug Fixes:

* Fixed a typo in the query parameter `newProposal` in multiple files to ensure correct fetching and handling of new proposals. ([apps/web/app/(app)/gardens/[chain]/[garden]/[community]/[poolId]/page.tsxL77-R89](diffhunk://#diff-61362aff1ab8473768382f4bd8c056d2855f68902284980e5d4532a7d62f6273L77-R89), [[1]](diffhunk://#diff-9f2974bf619e035b43f2ad6d4c3ae53c0943d8e2d516380051a4fdcb38314d0bR218-L229) [[2]](diffhunk://#diff-64bffd3d49892d55561619a6dc05d0650673553b4b4ba946a72ea17cf5dd8b25L50-R81)
* Added error handling for IPFS content fetching in `apps/web/app/api/ipfs/[hash]/route.ts` to return a detailed error response. ([apps/web/app/api/ipfs/[hash]/route.tsR18-R30](diffhunk://#diff-ecf7e3a2229c222899d992c4116c6b4ec12dd8bb95ee8fdb904cd30f556f53d3R18-R30))

### Component Updates:

* Updated the `ProposalCard` component to fetch metadata using `useMetadataIpfsFetch` and display a skeleton loader while loading. [[1]](diffhunk://#diff-64bffd3d49892d55561619a6dc05d0650673553b4b4ba946a72ea17cf5dd8b25L7-R38) [[2]](diffhunk://#diff-64bffd3d49892d55561619a6dc05d0650673553b4b4ba946a72ea17cf5dd8b25L50-R81) [[3]](diffhunk://#diff-64bffd3d49892d55561619a6dc05d0650673553b4b4ba946a72ea17cf5dd8b25L103-L107)
* Modified the `PoolGovernance` component to use the `CVStrategy` type from `#subgraph/.graphclient` for better type safety.

### UI Improvements:

* Adjusted the `PoolHeader` component to fix an HTML structure issue.
* Enhanced the `ProposalCard` component to apply a stronger shadow effect when a new proposal is added.

### CODE REVIEW

**Comment by Corantin** [comment]
!ai

**Comment by Corantin** [comment]
!ai

**Comment by Corantin** [comment]
!ai

**Comment by Corantin** [comment]
!ai

**Comment by Corantin** [comment]
!ai

**Comment by Corantin** [comment]
!ai

**Comment by Corantin** [comment]
!ai

**Comment by Corantin** [comment]
!ai

**Comment by Corantin** [comment]
!ai

**Comment by Corantin** [comment]
!ai

**Comment by Corantin** [comment]
!ai

**Comment by Corantin** [comment]
!ai

**Comment by Corantin** [comment]
!ai

**Comment by Corantin** [comment]
!ai

**Comment by Corantin** [comment]
!ai

**Comment by Corantin** [comment]
!ai

**Comment by Corantin** [comment]
!ai

**Comment by Corantin** [comment]
!ai

**Comment by Corantin** [comment]
!ai

**Comment by Corantin** [comment]
!ai

**Comment by Corantin** [comment]
!ai

**Comment by Corantin** [comment]
!ai

**Comment by Corantin** [comment]
ai

**Comment by Corantin** [comment]
!
ai

**Comment by Corantin** [comment]
!ai

**Comment by Corantin** [comment]
!ai

**Comment by Corantin** [comment]
!ai

**Comment by Corantin** [comment]
!ai

**Comment by Corantin** [comment]
!ai

**Review by Lucianosc — DISMISSED** [review]
LGTM

**Comment by Corantin** [comment]
!ai

**Review by Mati0x — APPROVED** [review]
test creating proposal. WORK VERY NICE! . great refactor!

**Pull request merged**
