### PR TITLE
Fixing-beta

### PR DESCRIPTION
**Pull request by Mati0x**
- [x] Allocate button: rename allocation button into "Submit your support!" or "Submit Allocation" 
- [x] Proposal page: chart scale should be based on threshold or max value like before
- [x] Adjust CVChart 
- [x] Signaling pools: remove minimum conviction from edit settings page
- [x] Signaling pools: remove spending limit from edit settings page
- [x] Signaling pools: remove threshold from edit settings page
- [x] Pool form: Token address input: Remove garden token as default address
- [x] Pool card: Adjust pool cards height based on content
- [x] Cards: always ellipsis when overflow

- [x] Bug: Display correct funding token for active pools (kev is on it!)
- [x] Manage support button in proposalId page to redirect to to pool page and opens manage support 

Suggestion:
- [x]  remove pool id  from PoolHeader (gonna do it in beta branch)

### CODE REVIEW

**Comment by Mati0x** [comment]
For ellipse when overflow, check with dev (is ok here) and merge this pr to beta 
For adjust pool id in pool header also merge pr into beta

**Review by Corantin — APPROVED** [review]

**Comment by Corantin** [comment]
Don't like the new card that wrapped the other cards  :S 
This PR:
image
Before:
image

**Review by Corantin — CHANGES_REQUESTED** [review]
Don't like the new card that wrapped the other cards  :S 
This PR:
image
Before:
image

**Comment by Mati0x** [comment]
> Don't like the new card that wrapped the other cards :S This PR: image Before: image

**Pull request merged**
